services:
  db:
    build: ./db
    container_name: postgres_rainpath
    restart: unless-stopped
    env_file:
     - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_rainpath:/var/lib/postgresql/data

volumes:
  postgres_rainpath:
